# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/huntingt/downloads/base.xdc

# Block Designs: bd/mmap/mmap.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mmap || ORIG_REF_NAME==mmap} -quiet] -quiet

# IP: bd/mmap/ip/mmap_processing_system7_0_0/mmap_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mmap_processing_system7_0_0 || ORIG_REF_NAME==mmap_processing_system7_0_0} -quiet] -quiet

# IP: bd/mmap/ip/mmap_rgb2dvi_0_0/mmap_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mmap_rgb2dvi_0_0 || ORIG_REF_NAME==mmap_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/mmap/ip/mmap_clk_wiz_0/mmap_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mmap_clk_wiz_0 || ORIG_REF_NAME==mmap_clk_wiz_0} -quiet] -quiet

# IP: bd/mmap/ip/mmap_videogen_0_0/mmap_videogen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mmap_videogen_0_0 || ORIG_REF_NAME==mmap_videogen_0_0} -quiet] -quiet

# IP: bd/mmap/ip/mmap_vidsel_0_0/mmap_vidsel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mmap_vidsel_0_0 || ORIG_REF_NAME==mmap_vidsel_0_0} -quiet] -quiet

# IP: bd/mmap/ip/mmap_xlconstant_0_0/mmap_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mmap_xlconstant_0_0 || ORIG_REF_NAME==mmap_xlconstant_0_0} -quiet] -quiet

# IP: bd/mmap/ip/mmap_blk_mem_gen_0_0/mmap_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mmap_blk_mem_gen_0_0 || ORIG_REF_NAME==mmap_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/mmap/ip/mmap_linetest_0_0/mmap_linetest_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mmap_linetest_0_0 || ORIG_REF_NAME==mmap_linetest_0_0} -quiet] -quiet

# IP: bd/mmap/ip/mmap_blk_mem_gen_0_1/mmap_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mmap_blk_mem_gen_0_1 || ORIG_REF_NAME==mmap_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/mmap/ip/mmap_graphics_0_0/mmap_graphics_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mmap_graphics_0_0 || ORIG_REF_NAME==mmap_graphics_0_0} -quiet] -quiet

# XDC: bd/mmap/mmap_ooc.xdc
