# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/huntingt/repos/hdmi_mmap/hdmi_mmap.srcs/sources_1/bd/mmap/ip/mmap_div_gen_1_0/mmap_div_gen_1_0.xci
# IP: The module: 'mmap_div_gen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/huntingt/repos/hdmi_mmap/hdmi_mmap.srcs/sources_1/bd/mmap/ip/mmap_div_gen_1_0/mmap_div_gen_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmap_div_gen_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/huntingt/repos/hdmi_mmap/hdmi_mmap.srcs/sources_1/bd/mmap/ip/mmap_div_gen_1_0/mmap_div_gen_1_0.xci
# IP: The module: 'mmap_div_gen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/huntingt/repos/hdmi_mmap/hdmi_mmap.srcs/sources_1/bd/mmap/ip/mmap_div_gen_1_0/mmap_div_gen_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmap_div_gen_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
