webtalk_init -webtalk_dir /home/huntingt/repos/hdmi_mmap/hdmi_mmap.sim/sim_1/behav/xsim/xsim.dir/mmap_wrapper_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jan 23 20:40:21 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dd4cb29e-ed79-4f77-942e-629dd4b88af2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1756b8e9ebef4674ad6ec19692ada795" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Pop!_OS 18.10" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1796.014 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2903323 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "15" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "930.24_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5411384_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3054029175 -regid "" -xml /home/huntingt/repos/hdmi_mmap/hdmi_mmap.sim/sim_1/behav/xsim/xsim.dir/mmap_wrapper_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/huntingt/repos/hdmi_mmap/hdmi_mmap.sim/sim_1/behav/xsim/xsim.dir/mmap_wrapper_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/huntingt/repos/hdmi_mmap/hdmi_mmap.sim/sim_1/behav/xsim/xsim.dir/mmap_wrapper_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
